### ISSUE TITLE
Error when not flying and teleport to gass giant

### ISSUE THREAD

**Issue by Wolphin5** [Emphasia/DSP-Mods#2]
When I am standing on the ground, and select teleport to a gas giant, it throws the error message, and shows the Mecha standing on the "surface" of the gas giant.

This error is repeatable and has happened several times.

![image](https://user-images.githubusercontent.com/44385601/131435586-b6497fb4-aaa6-43b4-a4e8-7ae2df16698f.png)

Error message text

> The game has occured an error!  Please save the game as a copy immediately to see if this error remains, try opening the previous auto-save.
> NullReferenceException: Object reference not set to an instance of an object.
> PlayerFootsteps.PlayFootstepEffect(System.Boolean lr, System.Single biomo, System.Boolean water) (at << Location >>)
> PlayerFootsteps.LateUpdate() (at << Location >>)

Maybe add a check to see if teleporting to a Gas Giant, and if so, set flying before teleporting?

**Comment by Emphasia** [comment]
It works fine with my game save, maybe you can provide your game save along with destination if possible.
I did encounter the problem you described before. Enabling the flying mode and adjusting the landing altitude is the solution I adopted to solve it. However, you still encounter this problem, so I guess it may be due to the situation where Icarus was teleported before taking off...

**Comment by Wolphin5** [comment]
https://1drv.ms/u/s!Aoh2uloq1blDgtB2j5L6GyJHuUA1JA?e=lABpVD is the savegame after the 2nd time I had the error.

Think I was on Sargas II (or might have been I, III, or V) standing still and was going to Sargas IV.

**Comment by Emphasia** [comment]
Still no errors were observed, but the landing did become unstable.
What is your FPS? Mine is about 15.
The code is currently hooked on LateUpdate() where the frame is being updated, it seems that errors are more likely to happen when the FPS is low.

**Comment by Wolphin5** [comment]
Found it is when you try to move after arriving... if you don't immediatly fly.  Was moving from Sargas II to Sargas IV, and had it do it 3 times.

**Comment by Wolphin5** [comment]
I am thinking, that from the error, since you are not suposed to be able to stand on a gas giant, when it tries to run the footstep effect, it throws the error.

If I am flying before I teleport to the gas giant, it doesn't throw the error, nor does it allow landing.  

I wonder if there was a way to capture that error within the plugin, and when it throws the error, force flying and silently disreguard the error?

I turned on the FPS setting, and didn't see a drop from the 60 fps (+/- under 5).  I am running a GeFOrce GTX 1080 FTW2 DT video card, and not seeing the issue.

**Comment by Wolphin5** [comment]
This ticket was not closed, but just confirmed that it has been resolved with the current version when I tested.
