### ISSUE TITLE
error occurred after Version 0.8.22.9331

### ISSUE THREAD

**Issue by Wolphin5** [Emphasia/DSP-Mods#3]
I have now been getting the following error every time I try to teliport between the planets, doesn't matter how close or far away.

I have had to disable the plugin, so I can use the navigation and warping to other stars.

![image](https://user-images.githubusercontent.com/44385601/139566279-5cb748a2-60a0-4883-969f-a4ccf5ad8b87.png)

**Comment by rumpled** [comment]
Also experiencing this. It started within the last week or two.
Tried disabling all mods except for TelePotter and loaded a vanilla-compatible save. I still receive this error when trying to teleport to any planet.

**Comment by Emphasia** [comment]
[TelePotter.fix.zip](https://github.com/Emphasia/DSP-Mods/files/7492129/TelePotter.zip)

I temporarily disabled the navigation indicator, Please test and let me know if you still encounter that error.

**Comment by Wolphin5** [comment]
> I temporarily disabled the navigation indicator, Please test and let me know if you still encounter that error.
Loaded the attached DLL, to replace the plugin DLL that I had downloaded.
I can confirm for me that this fixes this issue, thanks!  Not sure if you want any further testing.

While standing on a rocky surface and teleporting to a gas giant, as reported in error #2.

**Comment by Wolphin5** [comment]
hmmm... seem to be having issues with teleporting between systems.  it seems to be failing when doing that, but hopping between planets in the same system is working without issue.

At times, getting the error, and having the teleport take several minutes to complete:
![image](https://user-images.githubusercontent.com/44385601/140662952-eb4646af-1b6f-4a1a-8f73-9b4787e5dd7c.png)

**Comment by Emphasia** [comment]
[TelePotter.fix.zip](https://github.com/Emphasia/DSP-Mods/files/7504318/TelePotter.zip)

try this one..

**Comment by Wolphin5** [comment]
This fix appears to have resolved.  I have teleported through several inter-system jumps without issue, and planet to planet is also working.

**Comment by Emphasia** [comment]
updated in [the store](https://dsp.thunderstore.io/package/Emphasia/TelePotter/1.2.1/).
