### ISSUE TITLE
传送后原来所在的星系会在外太空中变得奇大无比

### ISSUE THREAD

**Issue by SavitarC** [Emphasia/DSP-Mods#4]
传送后原来所在的星系会在外太空中变得奇大无比
[![I0oEjI.png](https://z3.ax1x.com/2021/11/11/I0oEjI.png)](https://imgtu.com/i/I0oEjI)

**Comment by Emphasia** [comment]
是新的1.2.1版本开始出现的BUG吗..

**Comment by SavitarC** [comment]
是的...似乎跟点击传送后立马关闭星图有关（不太确定），有一定概率出现这种bug

**Comment by SavitarC** [comment]
> 是新的1.2.1版本开始出现的BUG吗..

是的...似乎跟点击传送后立马关闭星图有关（不太确定），有一定概率出现这种bug

**Comment by Emphasia** [comment]
听起来好像不是特别要命的BUG 可以的话等过两天有空了我再琢磨琢磨

**Comment by SavitarC** [comment]
> 听起来好像不是特别要命的BUG 可以的话等过两天有空了我再琢磨琢磨

哈哈，确实不是很要紧，只是说有点诡异，现在还出现了这种光带。辛苦你了
[![Ir3pX6.png](https://z3.ax1x.com/2021/11/12/Ir3pX6.png)](https://imgtu.com/i/Ir3pX6)

**Comment by Emphasia** [comment]
确实好诡异
可以帮我注意一下复现的条件 知道触发条件定位修复起来会方便很多

**Comment by Emphasia** [comment]
> > 听起来好像不是特别要命的BUG 可以的话等过两天有空了我再琢磨琢磨
> 
> 哈哈，确实不是很要紧，只是说有点诡异，现在还出现了这种光带。辛苦你了

确实好诡异
可以帮我注意一下复现的条件 知道触发条件定位修复起来会方便很多

**Comment by SavitarC** [comment]
> > > 听起来好像不是特别要命的BUG 可以的话等过两天有空了我再琢磨琢磨
> > 
> > 
> > 哈哈，确实不是很要紧，只是说有点诡异，现在还出现了这种光带。辛苦你了
> 
> 确实好诡异 可以帮我注意一下复现的条件 知道触发条件定位修复起来会方便很多

又测试了多次,感觉像是距离恒星较近的时候进行传送，会出现这种横移光圈
[![IralfU.png](https://z3.ax1x.com/2021/11/12/IralfU.png)](https://imgtu.com/i/IralfU)
然后就会出现bug。在较远处传送的时候一般就不会出现

**Comment by Emphasia** [comment]
立马关星图和恒星边传送都试了 复现不了 😂

**Comment by SavitarC** [comment]
> 立马关星图和恒星边传送都试了 复现不了 😂

啊这，那我也不知道了，把其他的mod全部移除之后依然存在这个bug，而且只要是靠近恒星传送100%触发。不过无关紧要，能跑就行XD   反正非要在恒星边上传送的情况比较少，而且重新传送到这个星系或者重进存档就能复原

**Comment by Emphasia** [comment]
> > 立马关星图和恒星边传送都试了 复现不了 😂
> 
> 啊这，那我也不知道了，把其他的mod全部移除之后依然存在这个bug，而且只要是靠近恒星传送100%触发。不过无关紧要，能跑就行XD 反正非要在恒星边上传送的情况比较少，而且重新传送到这个星系或者重进存档就能复原

我再试试

**Comment by Emphasia** [comment]
虽然还是没复现你的问题 但你可以试试[1.2.2版本](https://dsp.thunderstore.io/package/Emphasia/TelePotter/1.2.2/)看有没有改善

**Comment by SavitarC** [comment]
> 虽然还是没复现你的问题 但你可以试试[1.2.2版本](https://dsp.thunderstore.io/package/Emphasia/TelePotter/1.2.2/)看有没有改善

2333辛苦了，虽然还是存在，但是既然你没法复现，那可能是和我个人的环境发生了一些奇妙的化学反应导致只有我才有这个bug吧，谢谢啦
