### ISSUE TITLE
Update 0.9.24.11286 crashes Teleporter

### ISSUE THREAD

**Issue by Chemie99** [Emphasia/DSP-Mods#6]
Game update to version 0.9.24.11286 broken Teleporter.
![image](https://user-images.githubusercontent.com/94768495/151411286-aed54e4e-9829-457a-a314-a936c1f89546.png)

Crashes when jumping to other systems, works in-system
Steps:
1. Teleport to new planet in new system
2. Gets stuck on "loading"
3. Hit "ESC"; you are back to original location
4. Try again to teleport
5. Crash (see attached)

**Comment by Wolphin5** [comment]
I have been having the same issue... and only when transporting between systems, not between planets in the same system.

I just did have it eventually arrive (letting it sit while doing this note), but it gave errors before it did...
![image](https://user-images.githubusercontent.com/44385601/151461998-44cfff76-7b40-4945-b76e-0245c3bc07c0.png)

**Comment by Emphasia** [comment]
https://dsp.thunderstore.io/package/download/Emphasia/TelePotter/1.2.3/
new version uploaded.

**Comment by Chemie99** [comment]
> https://dsp.thunderstore.io/package/download/Emphasia/TelePotter/1.2.3/ new version uploaded.

Thanks.  Resolved for me!
